# Generated by Django 3.2.7 on 2021-11-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FibHistory',
        ),
    ]
